"use client";

import { useState, useEffect, useMemo, useCallback } from "react";
import { request } from "@/utils/api";
import { motion, AnimatePresence } from "framer-motion";
import { API_BASE_URL } from "@/utils/runtimeConfig";
import {
  WILD_BASE,
  WILD_SPECIAL,
  ISLAND_IMPRINTS,
  RUNE_GRADES,
  RUNE_TYPES,
  RPG_MAT_LIST,
  RPG_WEAPON_INFO,
  RPG_SKILL_SYSTEM
} from "./marketData";

type PaginationState = {
  page: number;
  total: number;
  hasMore: boolean;
};

const DEFAULT_PAGINATION: PaginationState = { page: 1, total: 0, hasMore: false };

export default function AdminTab({ items: initialItems }: { items: any[] }) {
  // --- 상태 관리 ---
  const [items, setItems] = useState(initialItems);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [variables, setVariables] = useState<any[]>([]);
  const [marketHistory, setMarketHistory] = useState<any[]>([]);
  const [historyPagination, setHistoryPagination] = useState<PaginationState>(DEFAULT_PAGINATION);
  const [isHistoryLoading, setIsHistoryLoading] = useState(false);

  const [activeManageTab, setActiveManageTab] = useState<"ENGINE" | "DATABASE" | "HISTORY">("ENGINE");
  const [activeVarTab, setActiveVarTab] = useState<string>("RPG");

  // 💡 아이템 추가 폼 상태
  const [isAddingItem, setIsAddingItem] = useState(false);
  const [newItem, setNewItem] = useState({ name: "", category: "WILD" });
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  // 💡 데이터 주입 폼 상태
  const [form, setForm] = useState({
    price: "",
    tradeDate: new Date().toISOString().split('T')[0],
    level: 0,
    rank: "입문",
    enchantments: {} as Record<string, number>,
    imprints: {} as Record<string, number>,
    skills: {} as Record<string, number>,
    runes: [{ grade: "", type: "" }, { grade: "", type: "" }, { grade: "", type: "" }]
  });

  /**
   * 🛠️ [패치] 이미지 경로 보안 처리 (Mixed Content 에러 방지)
   */
  const getSecureUrl = (url: string) => {
    if (!url) return "";
    return url.replace("http://", "https://");
  };

  const triggerHaptic = useCallback(() => {
    if (typeof window !== "undefined" && window.navigator?.vibrate) {
      window.navigator.vibrate(10);
    }
  }, []);

  const currentWeaponSkillConfig = useMemo(() => {
    if (!selectedItem) return null;
    const weaponGroup = Object.keys(RPG_SKILL_SYSTEM).find(key => selectedItem.name.includes(key));
    return weaponGroup ? RPG_SKILL_SYSTEM[weaponGroup] : null;
  }, [selectedItem]);

  // --- 데이터 로드 로직 ---
  const fetchItems = useCallback(async () => {
    const data = await request("/api/admin/items");
    if (Array.isArray(data)) setItems(data);
  }, []);

  const fetchVariables = useCallback(async () => {
    const data = await request("/api/admin/market/variables");
    if (Array.isArray(data)) setVariables(data);
  }, []);

  const fetchMarketHistory = useCallback(async (page = 1, append = false) => {
    setIsHistoryLoading(true);
    try {
      const data = await request(`/api/admin/market/history?page=${page}&limit=30`);
      if (Array.isArray(data)) {
        setMarketHistory(data);
        setHistoryPagination({ page: 1, total: data.length, hasMore: false });
        return;
      }
      const items = Array.isArray(data?.items) ? data.items : [];
      setMarketHistory((prev) => append ? [...prev, ...items] : items);
      setHistoryPagination(data?.pagination || { page, total: items.length, hasMore: false });
    } finally {
      setIsHistoryLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchVariables();
    fetchMarketHistory();
    if (items.length === 0) fetchItems();
  }, [fetchVariables, fetchMarketHistory, fetchItems]);

  // --- 🛠️ [패치] 시세 변수 프리셋 생성 로직 ---
  const autoGeneratedKeys = useMemo(() => {
    const keys: { key: string, label: string, category: string }[] = [];

    // 1. RPG 섹션: 무기 종류별 순정가 및 랭크별 최저가
    if (activeVarTab === "RPG") {

      // 1. 🛠️ 인장 및 문장 변수
      keys.push({ key: "MAT_RPG_해방의 인장", label: "해방의 인장 (슬롯용) 단가", category: "RPG" });
      keys.push({ key: "MAT_RPG_개방의 문장", label: "개방의 문장 (스킬용) 단가", category: "RPG" });
      const weaponTypes = ["스태프", "망치", "총", "활", "창", "대검"];
      weaponTypes.forEach(typeName => {
        keys.push({ key: `MAT_RPG_BASE_${typeName}`, label: `${typeName} 종류 순정 시세`, category: "RPG" });
      });

      RUNE_TYPES.forEach(type => {
        RUNE_GRADES.forEach(grade => {
          keys.push({ key: `MAT_RUNE_${type}_${grade}`, label: `${type} [${grade}]`, category: "RPG" });
        });
      });
      RPG_MAT_LIST.forEach(name => {
        keys.push({ key: `MAT_RPG_${name}`, label: `${name} 단가`, category: "RPG" });
      });
      ["입문", "견습", "정예", "영웅"].forEach(rank => {
        keys.push({ key: `MAT_RPG_BASE_${rank}`, label: `${rank} 랭크 최저가`, category: "RPG" });
      });
    }

    // 2. ISLAND 섹션
    if (activeVarTab === "ISLAND") {
      keys.push({ key: "MAT_ISLAND_CONTRACT", label: "각인 계약서 단가", category: "ISLAND" });
      keys.push(
        { key: "MAT_STONE_LOW", label: "라이프스톤(하)", category: "ISLAND" },
        { key: "MAT_STONE_MID", label: "라이프스톤(중)", category: "ISLAND" },
        { key: "MAT_STONE_HIGH", label: "라이프스톤(상)", category: "ISLAND" }
      );
      ISLAND_IMPRINTS.forEach(name => {
        keys.push({ key: `MAT_SCROLL_투박한_${name}`, label: `투박한 ${name} 시세`, category: "ISLAND" });
      });
    }

    // 3. WILD 섹션: 일반 인챈트 및 상급 한계돌파용 변수
    if (activeVarTab === "WILD") {
      [...WILD_BASE, ...WILD_SPECIAL].forEach(([name]) => {
        keys.push({ key: `MAT_BOOK_${name}`, label: `${name} (일반 10%)`, category: "WILD" });
      });

      // 상급 인챈트가 존재하는 6종
      const HIGH_BOOKS = [
        { name: "날카로움", label: "상급 날카로움 (5→7)" },
        { name: "미끼", label: "상급 미끼 (3→5)" },
        { name: "보호", label: "상급 보호 (4→6)" },
        { name: "약탈", label: "상급 약탈 (3→5)" },
        { name: "행운", label: "상급 행운 (3→5)" },
        { name: "효율", label: "상급 효율 (5→10)" }
      ];

      HIGH_BOOKS.forEach(book => {
        keys.push({ key: `MAT_HIGH_BOOK_${book.name}`, label: `${book.label} 시세`, category: "WILD" });
        keys.push({ key: `MAT_HIGH_RATE_${book.name}`, label: `${book.name} 상급 확률(%)`, category: "WILD" });
      });
    }
    return keys;
  }, [activeVarTab]);

  const handleUpdateVar = async (key: string, value: string, category: string, label: string) => {
    await request("/api/admin/market/variables", {
      method: 'POST',
      body: JSON.stringify({ key, value: value || "0", category, label })
    });
    setVariables(prev => {
      const exists = prev.find(v => v.key === key);
      const numVal = parseFloat(value) || 0;
      if (exists) return prev.map(v => v.key === key ? { ...v, value: numVal } : v);
      return [...prev, { key, value: numVal, category, label }];
    });
  };

  const handleItemSelect = (itemId: number) => {
    triggerHaptic();
    const item = items.find(i => i.id === itemId);
    setSelectedItem(item);
    if (item && item.category.toUpperCase().includes("RPG")) {
      const weaponGroup = Object.keys(RPG_WEAPON_INFO).find(key => item.name.includes(key));
      if (weaponGroup) setForm(prev => ({ ...prev, rank: RPG_WEAPON_INFO[weaponGroup].rank }));
    }
    setForm(prev => ({ ...prev, price: "", enchantments: {}, imprints: {}, skills: {}, level: 0 }));
  };

  const toggleSkill = (skillName: string) => {
    triggerHaptic();
    setForm(prev => {
      const currentLevel = prev.skills[skillName] || 0;
      const nextLevel = currentLevel >= 7 ? 0 : currentLevel + 1;
      const newSkills = { ...prev.skills };

      if (nextLevel === 0) {
        delete newSkills[skillName];
      } else {
        if (!prev.skills[skillName] && Object.keys(newSkills).length >= 4) {
          alert("전투 스킬은 최대 4개까지만 설정 가능합니다.");
          return prev;
        }
        newSkills[skillName] = nextLevel;
      }
      return { ...prev, skills: newSkills };
    });
  };

  const handleCreateItem = async () => {
    if (!newItem.name || !selectedFile) return alert("정보를 모두 입력하세요.");
    const formData = new FormData();
    formData.append("name", newItem.name);
    formData.append("category", newItem.category);
    formData.append("image", selectedFile);

    setIsLoading(true);
    try {
      const res = await fetch(`${API_BASE_URL}/api/admin/items`, {
        method: "POST",
        headers: { "Authorization": `Bearer ${localStorage.getItem("token")}` },
        body: formData
      });

      if (res.ok) {
        setIsAddingItem(false);
        setNewItem({ name: "", category: "WILD" });
        setSelectedFile(null);
        await fetchItems();
        alert("아이템 등록 성공");
      }
    } catch (err) {
      alert("등록 실패");
    } finally {
      setIsLoading(false);
    }
  };

  const purgeItem = async (itemId: number) => {
    if (!confirm("정말 삭제하시겠습니까?")) return;
    await request(`/api/admin/items/${itemId}`, { method: "DELETE" });
    fetchItems();
  };

  const purgeHistory = async (historyId: number) => {
    triggerHaptic();
    if (!confirm("기록을 영구 삭제합니까?")) return;
    try {
      await request(`/api/admin/market/history/${historyId}`, { method: "DELETE" });
      setMarketHistory(prev => prev.filter(h => h.id !== historyId));
      setHistoryPagination((prev) => ({ ...prev, total: Math.max(0, prev.total - 1) }));
    } catch (err) { alert("삭제 실패"); }
  };

  const handleSubmitHistory = async () => {
    if (!selectedItem || !form.price) return alert("필수 정보를 입력하세요.");
    setIsLoading(true);
    try {
      await request('/api/admin/market/history/inject', {
        method: 'POST',
        body: JSON.stringify({
          itemId: selectedItem.id, price: form.price, tradeDate: form.tradeDate,
          enhancementLevel: form.level, enhancementRank: form.rank,
          enchantments: form.enchantments, imprint: form.imprints,
          skills: form.skills, runes: form.runes
        })
      });
      setForm({ ...form, price: "", enchantments: {}, imprints: {}, skills: {} });
      fetchMarketHistory();
      alert("데이터 주입 성공");
    } catch (err) { alert("주입 실패"); } finally { setIsLoading(false); }
  };

  return (
    <div className="space-y-4">
      <div className="flex w-fit gap-1 rounded-xl border border-white/5 bg-black/35 p-1">
        {[{ id: "ENGINE", label: "시세 엔진 & 주입" }, { id: "DATABASE", label: "아이템 관리" }, { id: "HISTORY", label: "거래 기록" }].map(tab => (
          <button key={tab.id} onClick={() => setActiveManageTab(tab.id as any)} className={`rounded-lg px-4 py-2 text-xs font-semibold transition-all ${activeManageTab === tab.id ? "bg-white text-black" : "text-zinc-500 hover:text-zinc-200"}`}>
            {tab.label}
          </button>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {activeManageTab === "ENGINE" && (
          <motion.div key="engine" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
            {/* 시세 변수 설정 구역 */}
            <section className="rounded-[24px] border border-blue-500/15 bg-white/[0.018] p-4 backdrop-blur-md md:p-5">
              <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <h3 className="text-sm font-extrabold tracking-[-0.02em] text-blue-300">
                  시세 변수
                </h3>
                <div className="flex w-fit gap-1 rounded-xl bg-black/40 p-1">
                  {["RPG", "ISLAND", "WILD"].map(tab => (
                    <button key={tab} onClick={() => setActiveVarTab(tab)} className={`rounded-lg px-4 py-1.5 text-[10px] font-semibold transition-all ${activeVarTab === tab ? "bg-blue-600 text-white" : "text-zinc-600 hover:text-zinc-300"}`}>{tab}</button>
                  ))}
                </div>
              </div>
              <div className="grid max-h-[320px] grid-cols-2 gap-2 overflow-y-auto pr-1 custom-scrollbar md:grid-cols-4 xl:grid-cols-6">
                {autoGeneratedKeys.map((preset) => {
                  const dbValue = variables.find(v => v.key === preset.key);
                  return (
                    <div key={preset.key} className="flex flex-col gap-1 rounded-xl border border-white/5 bg-black/35 p-3 transition-all focus-within:border-blue-500/50">
                      <span className="truncate text-[10px] font-medium text-zinc-500">{preset.label}</span>
                      <div className="flex items-center gap-1.5">
                        <input type="text" className="w-full bg-transparent font-mono text-xs font-semibold text-blue-300 outline-none" defaultValue={dbValue?.value || ""} onBlur={(e) => handleUpdateVar(preset.key, e.target.value, preset.category, preset.label)} placeholder="0" />
                        <span className="text-[10px] font-medium text-zinc-700">G</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>

            {/* 데이터 주입 구역 */}
            <section className="grid grid-cols-1 gap-4 lg:grid-cols-2">
              <div className="space-y-4 rounded-[24px] border border-red-500/15 bg-white/[0.018] p-4 md:p-5">
                <div className="text-sm font-extrabold tracking-[-0.02em] text-red-300">
                  거래 데이터 주입
                </div>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <label className="ml-1 text-[10px] font-semibold text-zinc-600">대상 아이템</label>
                    <select className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2.5 text-xs font-medium text-zinc-300 outline-none" onChange={(e) => handleItemSelect(parseInt(e.target.value))}>
                      <option value="">아이템 선택...</option>
                      {items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}
                    </select>
                  </div>
                  <div className="space-y-1.5">
                    <label className="ml-1 text-[10px] font-semibold text-zinc-600">거래일</label>
                    <input type="date" className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2.5 font-mono text-xs text-zinc-300 outline-none" value={form.tradeDate} onChange={e => setForm({ ...form, tradeDate: e.target.value })} />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <label className="ml-1 text-[10px] font-semibold text-zinc-600">거래가</label>
                  <input type="text" placeholder="0" className="w-full rounded-2xl border border-white/10 bg-black/40 px-4 py-3 font-mono text-2xl font-semibold text-yellow-400 outline-none" value={form.price} onChange={e => setForm({ ...form, price: e.target.value.replace(/[^0-9]/g, '') })} />
                </div>
                <button onClick={handleSubmitHistory} disabled={isLoading} className="site-btn site-btn-danger w-full">
                  {isLoading ? "처리 중..." : "거래 데이터 주입"}
                </button>
              </div>

              {/* 세부 옵션 설정 (오른쪽 패널) */}
              <div className="max-h-[440px] overflow-y-auto rounded-[24px] border border-white/5 bg-black/35 p-4 custom-scrollbar md:p-5">
                {selectedItem ? (
                  <div className="space-y-5">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-semibold text-zinc-500">강화 단계</span>
                      <span className="text-base font-semibold text-white">+{form.level}</span>
                    </div>
                    <input type="range" min="0" max="15" value={form.level} onChange={e => setForm({ ...form, level: parseInt(e.target.value) })} className="calc-range calc-range-red" />

                    {selectedItem.category.toUpperCase().includes("RPG") && currentWeaponSkillConfig && (
                      <div className="space-y-3 border-t border-white/5 pt-4">
                        <div className="text-[11px] font-semibold text-purple-300">전투 스킬</div>
                        <div className="grid grid-cols-2 gap-2">
                          {Object.keys(currentWeaponSkillConfig.skills).map(name => (
                            <button key={name} onClick={() => toggleSkill(name)} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 transition-all ${form.skills[name] ? "border-purple-400 bg-purple-600 text-white" : "border-transparent bg-white/5 text-zinc-600 hover:text-zinc-300"}`}>
                              <span className="text-xs font-semibold">{name}</span>
                              {form.skills[name] && <span className="rounded-md bg-white/20 px-2 py-0.5 text-[10px] font-semibold">Lv.{form.skills[name]}</span>}
                            </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ) : <div className="flex min-h-[240px] items-center justify-center text-xs font-medium text-zinc-700">아이템 선택 후 옵션을 설정할 수 있습니다.</div>}
              </div>
            </section>
          </motion.div>
        )}

        {activeManageTab === "DATABASE" && (
          <motion.div key="database" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4 rounded-[24px] border border-white/5 bg-white/[0.018] p-4 md:p-5">
            <div className="flex items-center justify-between gap-3">
              <div className="text-sm font-extrabold tracking-[-0.02em] text-zinc-100">
                아이템 데이터베이스
              </div>
              <button
                onClick={() => { triggerHaptic(); setIsAddingItem(!isAddingItem); }}
                className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${isAddingItem ? "bg-zinc-800 text-zinc-500" : "bg-cyan-600 text-white"}`}
              >
                {isAddingItem ? "닫기" : "아이템 추가"}
              </button>
            </div>

            {/* 아이템 추가 폼 */}
            <AnimatePresence>
              {isAddingItem && (
                <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="grid grid-cols-1 gap-3 overflow-hidden rounded-2xl border border-white/10 bg-black/40 p-4 md:grid-cols-4">
                  <div className="space-y-1.5">
                    <label className="ml-1 text-[10px] font-semibold text-zinc-600">아이콘</label>
                    <input type="file" accept="image/*" onChange={e => setSelectedFile(e.target.files?.[0] || null)} className="w-full rounded-xl border border-white/5 bg-zinc-900/50 p-2 text-[10px] text-zinc-400 outline-none" />
                  </div>
                  <div className="space-y-1.5">
                    <label className="ml-1 text-[10px] font-semibold text-zinc-600">아이템명</label>
                    <input type="text" placeholder="아이템명..." value={newItem.name} onChange={e => setNewItem({ ...newItem, name: e.target.value })} className="w-full rounded-xl border border-white/5 bg-zinc-900/50 px-3 py-2.5 text-xs font-medium text-white outline-none focus:border-cyan-500/50" />
                  </div>
                  <div className="space-y-1.5">
                    <label className="ml-1 text-[10px] font-semibold text-zinc-600">카테고리</label>
                    <select value={newItem.category} onChange={e => setNewItem({ ...newItem, category: e.target.value })} className="w-full rounded-xl border border-white/5 bg-zinc-900/50 px-3 py-2.5 text-xs font-medium text-white outline-none focus:border-cyan-500/50">
                      <option value="WILD">야생 (WILD)</option>
                      <option value="ISLAND">아일랜드 (ISLAND)</option>
                      <option value="RPG">RPG 무기</option>
                      <option value="ETC">기타 아이템 (ETC)</option>
                    </select>
                  </div>
                  <button onClick={handleCreateItem} disabled={isLoading} className="site-btn site-btn-primary self-end">
                    {isLoading ? "등록 중..." : "등록"}
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* 아이템 리스트 */}
            <div className="max-h-[520px] space-y-1.5 overflow-y-auto pr-1 custom-scrollbar">
              {items.map(item => (
                <div key={item.id} className="group flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-black/35 p-3 transition-colors hover:bg-white/[0.025]">
                  <div className="flex min-w-0 items-center gap-3">
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-white/5 bg-zinc-900 p-2">
                      <img src={getSecureUrl(item.iconUrl)} className="w-full h-full object-contain pixel-art" alt={item.name} />
                    </div>
                    <div className="min-w-0">
                      <div className="truncate text-xs font-semibold text-zinc-200">{item.name}</div>
                      <div className="mt-0.5 text-[10px] font-medium text-zinc-600">{item.category}</div>
                    </div>
                  </div>
                  <div className="flex shrink-0 items-center gap-3">
                    <span className="font-mono text-[10px] text-zinc-700">#{item.id}</span>
                    <button onClick={() => purgeItem(item.id)} className="site-btn site-btn-danger site-btn-compact">삭제</button>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* 거래 기록 관리 탭 */}
        {activeManageTab === "HISTORY" && (
          <motion.div key="history" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="overflow-hidden rounded-[24px] border border-white/5 bg-white/[0.018]">
            <div className="flex items-center justify-between border-b border-white/5 p-4 text-sm font-extrabold tracking-[-0.02em] text-zinc-100 md:p-5">
              <span>전체 거래 기록 리스트</span>
              <span className="text-[10px] font-semibold text-zinc-600">
                {marketHistory.length.toLocaleString()} / {historyPagination.total.toLocaleString()} loaded
              </span>
            </div>
            <div className="overflow-x-auto custom-scrollbar">
              <table className="w-full min-w-[720px] text-left">
                <thead className="bg-white/[0.035] text-[10px] font-semibold text-zinc-600">
                  <tr>
                    <th className="px-4 py-3">아이템</th>
                    <th className="px-4 py-3">가격</th>
                    <th className="px-4 py-3">날짜</th>
                    <th className="px-4 py-3">상태</th>
                    <th className="px-4 py-3 text-right">관리</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {marketHistory.map(h => (
                    <tr key={h.id} className="group text-xs transition-colors hover:bg-white/[0.015]">
                      <td className="px-4 py-3 font-semibold text-zinc-300">
                        {h.item?.name} <span className="text-zinc-600 ml-1">+{h.enhancementLevel}</span>
                      </td>
                      <td className="px-4 py-3 font-mono text-sm font-semibold text-cyan-400">
                        {Number(h.price).toLocaleString()} G
                      </td>
                      <td className="px-4 py-3 font-mono text-[10px] text-zinc-500">
                        {new Date(h.tradeDate).toLocaleDateString()}
                      </td>
                      <td className="px-4 py-3">
                        <span className={`rounded-md border px-2.5 py-1 text-[9px] font-semibold ${h.isValid ? "bg-green-500/5 text-green-500 border-green-500/20" : "bg-red-500/5 text-red-500 border-red-500/20"}`}>
                          {h.isValid ? "유효" : "무효"}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <button onClick={() => purgeHistory(h.id)} className="site-btn site-btn-danger site-btn-compact">삭제</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {historyPagination.hasMore && (
              <div className="border-t border-white/5 p-4 text-center">
                <button
                  type="button"
                  onClick={() => fetchMarketHistory(historyPagination.page + 1, true)}
                  disabled={isHistoryLoading}
                  className="site-btn site-btn-secondary"
                >
                  {isHistoryLoading ? "불러오는 중..." : "거래 기록 더 보기"}
                </button>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}