"use client";

import { useState, useEffect, useMemo, useCallback } from "react";
import { request } from "@/utils/api";
import { motion, AnimatePresence } from "framer-motion";
import {
  WILD_BASE,
  WILD_SPECIAL,
  ISLAND_IMPRINTS,
  RUNE_GRADES,
  RUNE_TYPES,
  RPG_MAT_LIST,
  RPG_WEAPON_INFO,
  RPG_SKILL_SYSTEM
} from "./marketData";

export default function AdminTab({ items: initialItems }: { items: any[] }) {
  // --- 상태 관리 ---
  const [items, setItems] = useState(initialItems);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [variables, setVariables] = useState<any[]>([]);
  const [marketHistory, setMarketHistory] = useState<any[]>([]);

  const [activeManageTab, setActiveManageTab] = useState<"ENGINE" | "DATABASE" | "HISTORY">("ENGINE");
  const [activeVarTab, setActiveVarTab] = useState<string>("RPG");

  // 💡 아이템 추가 폼 상태
  const [isAddingItem, setIsAddingItem] = useState(false);
  const [newItem, setNewItem] = useState({ name: "", category: "WILD" });
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  // 💡 데이터 주입 폼 상태
  const [form, setForm] = useState({
    price: "",
    tradeDate: new Date().toISOString().split('T')[0],
    level: 0,
    rank: "입문",
    enchantments: {} as Record<string, number>,
    imprints: {} as Record<string, number>,
    skills: {} as Record<string, number>,
    runes: [{ grade: "", type: "" }, { grade: "", type: "" }, { grade: "", type: "" }]
  });

  /**
   * 🛠️ [패치] 이미지 경로 보안 처리 (Mixed Content 에러 방지)
   */
  const getSecureUrl = (url: string) => {
    if (!url) return "";
    return url.replace("http://", "https://");
  };

  const triggerHaptic = useCallback(() => {
    if (typeof window !== "undefined" && window.navigator?.vibrate) {
      window.navigator.vibrate(10);
    }
  }, []);

  const currentWeaponSkillConfig = useMemo(() => {
    if (!selectedItem) return null;
    const weaponGroup = Object.keys(RPG_SKILL_SYSTEM).find(key => selectedItem.name.includes(key));
    return weaponGroup ? RPG_SKILL_SYSTEM[weaponGroup] : null;
  }, [selectedItem]);

  // --- 데이터 로드 로직 ---
  const fetchItems = useCallback(async () => {
    const data = await request("/api/admin/items");
    if (Array.isArray(data)) setItems(data);
  }, []);

  const fetchVariables = useCallback(async () => {
    const data = await request("/api/admin/market/variables");
    if (Array.isArray(data)) setVariables(data);
  }, []);

  const fetchMarketHistory = useCallback(async () => {
    const data = await request("/api/admin/market/history");
    if (Array.isArray(data)) setMarketHistory(data);
  }, []);

  useEffect(() => {
    fetchVariables();
    fetchMarketHistory();
    if (items.length === 0) fetchItems();
  }, [fetchVariables, fetchMarketHistory, fetchItems]);

  // --- 🛠️ [패치] 시세 변수 프리셋 생성 로직 ---
  const autoGeneratedKeys = useMemo(() => {
    const keys: { key: string, label: string, category: string }[] = [];

    // 1. RPG 섹션: 무기 종류별 순정가 및 랭크별 최저가
    if (activeVarTab === "RPG") {

      // 1. 🛠️ 인장 및 문장 변수 추가 (이 부분이 누락되었습니다)
      keys.push({ key: "MAT_RPG_해방의 인장", label: "해방의 인장 (슬롯용) 단가", category: "RPG" });
      keys.push({ key: "MAT_RPG_개방의 문장", label: "개방의 문장 (스킬용) 단가", category: "RPG" });
      const weaponTypes = ["스태프", "망치", "총", "활", "창", "대검"];
      weaponTypes.forEach(typeName => {
        keys.push({ key: `MAT_RPG_BASE_${typeName}`, label: `${typeName} 종류 순정 시세`, category: "RPG" });
      });

      RUNE_TYPES.forEach(type => {
        RUNE_GRADES.forEach(grade => {
          keys.push({ key: `MAT_RUNE_${type}_${grade}`, label: `${type} [${grade}]`, category: "RPG" });
        });
      });
      RPG_MAT_LIST.forEach(name => {
        keys.push({ key: `MAT_RPG_${name}`, label: `${name} 단가`, category: "RPG" });
      });
      ["입문", "견습", "정예", "영웅"].forEach(rank => {
        keys.push({ key: `MAT_RPG_BASE_${rank}`, label: `${rank} 랭크 최저가`, category: "RPG" });
      });
    }

    // 2. ISLAND 섹션
    if (activeVarTab === "ISLAND") {
      keys.push({ key: "MAT_ISLAND_CONTRACT", label: "각인 계약서 단가", category: "ISLAND" });
      keys.push(
        { key: "MAT_STONE_LOW", label: "라이프스톤(하)", category: "ISLAND" },
        { key: "MAT_STONE_MID", label: "라이프스톤(중)", category: "ISLAND" },
        { key: "MAT_STONE_HIGH", label: "라이프스톤(상)", category: "ISLAND" }
      );
      ISLAND_IMPRINTS.forEach(name => {
        keys.push({ key: `MAT_SCROLL_투박한_${name}`, label: `투박한 ${name} 시세`, category: "ISLAND" });
      });
    }

    // 3. WILD 섹션: 일반 인챈트 및 상급 한계돌파용 변수
    if (activeVarTab === "WILD") {
      [...WILD_BASE, ...WILD_SPECIAL].forEach(([name]) => {
        keys.push({ key: `MAT_BOOK_${name}`, label: `${name} (일반 10%)`, category: "WILD" });
      });

      // 상급 인챈트가 존재하는 특정 6종만 추가
      const HIGH_BOOKS = [
        { name: "날카로움", label: "상급 날카로움 (5→7)" },
        { name: "미끼", label: "상급 미끼 (3→5)" },
        { name: "보호", label: "상급 보호 (4→6)" },
        { name: "약탈", label: "상급 약탈 (3→5)" },
        { name: "행운", label: "상급 행운 (3→5)" },
        { name: "효율", label: "상급 효율 (5→10)" }
      ];

      HIGH_BOOKS.forEach(book => {
        keys.push({ key: `MAT_HIGH_BOOK_${book.name}`, label: `${book.label} 시세`, category: "WILD" });
        keys.push({ key: `MAT_HIGH_RATE_${book.name}`, label: `${book.name} 상급 확률(%)`, category: "WILD" });
      });
    }
    return keys;
  }, [activeVarTab]);

  const handleUpdateVar = async (key: string, value: string, category: string, label: string) => {
    await request("/api/admin/market/variables", {
      method: 'POST',
      body: JSON.stringify({ key, value: value || "0", category, label })
    });
    setVariables(prev => {
      const exists = prev.find(v => v.key === key);
      const numVal = parseFloat(value) || 0;
      if (exists) return prev.map(v => v.key === key ? { ...v, value: numVal } : v);
      return [...prev, { key, value: numVal, category, label }];
    });
  };

  const handleItemSelect = (itemId: number) => {
    triggerHaptic();
    const item = items.find(i => i.id === itemId);
    setSelectedItem(item);
    if (item && item.category.toUpperCase().includes("RPG")) {
      const weaponGroup = Object.keys(RPG_WEAPON_INFO).find(key => item.name.includes(key));
      if (weaponGroup) setForm(prev => ({ ...prev, rank: RPG_WEAPON_INFO[weaponGroup].rank }));
    }
    setForm(prev => ({ ...prev, price: "", enchantments: {}, imprints: {}, skills: {}, level: 0 }));
  };

  const toggleSkill = (skillName: string) => {
    triggerHaptic();
    setForm(prev => {
      const currentLevel = prev.skills[skillName] || 0;
      const nextLevel = currentLevel >= 7 ? 0 : currentLevel + 1;
      const newSkills = { ...prev.skills };

      if (nextLevel === 0) {
        delete newSkills[skillName];
      } else {
        if (!prev.skills[skillName] && Object.keys(newSkills).length >= 4) {
          alert("전투 스킬은 최대 4개까지만 설정 가능합니다.");
          return prev;
        }
        newSkills[skillName] = nextLevel;
      }
      return { ...prev, skills: newSkills };
    });
  };

  const handleCreateItem = async () => {
    if (!newItem.name || !selectedFile) return alert("정보를 모두 입력하세요.");
    const formData = new FormData();
    formData.append("name", newItem.name);
    formData.append("category", newItem.category);
    formData.append("image", selectedFile);

    setIsLoading(true);
    try {
      const BACKEND_URL = process.env.NEXT_PUBLIC_API_URL || "https://ddingtion-back.onrender.com";
      const res = await fetch(`${BACKEND_URL}/api/admin/items`, {
        method: "POST",
        headers: { "Authorization": `Bearer ${localStorage.getItem("token")}` },
        body: formData
      });

      if (res.ok) {
        setIsAddingItem(false);
        setNewItem({ name: "", category: "WILD" });
        setSelectedFile(null);
        await fetchItems();
        alert("아이템 등록 성공");
      }
    } catch (err) {
      alert("등록 실패");
    } finally {
      setIsLoading(false);
    }
  };

  const purgeItem = async (itemId: number) => {
    if (!confirm("정말 삭제하시겠습니까?")) return;
    await request(`/api/admin/items/${itemId}`, { method: "DELETE" });
    fetchItems();
  };

  const purgeHistory = async (historyId: number) => {
    triggerHaptic();
    if (!confirm("기록을 영구 삭제합니까?")) return;
    try {
      await request(`/api/admin/market/history/${historyId}`, { method: "DELETE" });
      setMarketHistory(prev => prev.filter(h => h.id !== historyId));
    } catch (err) { alert("삭제 실패"); }
  };

  const handleSubmitHistory = async () => {
    if (!selectedItem || !form.price) return alert("필수 정보를 입력하세요.");
    setIsLoading(true);
    try {
      await request('/api/auctions/inject-history', {
        method: 'POST',
        body: JSON.stringify({
          itemId: selectedItem.id, price: form.price, tradeDate: form.tradeDate,
          enhancementLevel: form.level, enhancementRank: form.rank,
          enchantments: form.enchantments, imprint: form.imprints,
          skills: form.skills, runes: form.runes
        })
      });
      setForm({ ...form, price: "", enchantments: {}, imprints: {}, skills: {} });
      fetchMarketHistory();
      alert("데이터 주입 성공");
    } catch (err) { alert("주입 실패"); } finally { setIsLoading(false); }
  };

  return (
    <div className="space-y-10">
      <div className="flex bg-black/40 p-1.5 rounded-2xl border border-white/5 w-fit mx-auto gap-1">
        {[{ id: "ENGINE", label: "시세 엔진 & 주입" }, { id: "DATABASE", label: "아이템 관리" }, { id: "HISTORY", label: "거래 기록" }].map(tab => (
          <button key={tab.id} onClick={() => setActiveManageTab(tab.id as any)} className={`px-8 py-2.5 rounded-xl text-xs font-black transition-all ${activeManageTab === tab.id ? "bg-white text-black" : "text-zinc-500 hover:text-zinc-200"}`}>
            {tab.label}
          </button>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {activeManageTab === "ENGINE" && (
          <motion.div key="engine" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-10">
            {/* 시세 변수 설정 구역 */}
            <section className="bg-white/[0.02] border border-blue-500/20 p-8 rounded-[40px] backdrop-blur-md">
              <div className="flex justify-between items-center mb-8 px-2">
                <h3 className="text-sm font-black text-blue-400 uppercase tracking-widest flex items-center gap-3">
                  <div className="w-1.5 h-3.5 bg-blue-500 rounded-full" /> Intelligence Core
                </h3>
                <div className="flex bg-black/40 p-1 rounded-xl gap-1">
                  {["RPG", "ISLAND", "WILD"].map(tab => (
                    <button key={tab} onClick={() => setActiveVarTab(tab)} className={`px-5 py-1.5 rounded-lg text-[10px] font-black transition-all ${activeVarTab === tab ? "bg-blue-600 text-white" : "text-zinc-600"}`}>{tab}</button>
                  ))}
                </div>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                {autoGeneratedKeys.map((preset) => {
                  const dbValue = variables.find(v => v.key === preset.key);
                  return (
                    <div key={preset.key} className="bg-black/40 border border-white/5 p-4 rounded-xl flex flex-col gap-1 focus-within:border-blue-500/50 transition-all">
                      <span className="text-[10px] text-zinc-500 font-bold truncate">{preset.label}</span>
                      <div className="flex items-center gap-2">
                        <input type="text" className="bg-transparent text-sm font-black font-mono text-blue-400 outline-none w-full" defaultValue={dbValue?.value || ""} onBlur={(e) => handleUpdateVar(preset.key, e.target.value, preset.category, preset.label)} placeholder="0" />
                        <span className="text-[10px] font-bold text-zinc-800">G</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>

            {/* 데이터 주입 구역 */}
            <section className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <div className="bg-white/[0.02] border border-red-500/20 p-8 rounded-[40px] space-y-6">
                <div className="text-sm font-black text-red-500 flex items-center gap-3">
                  <div className="w-1.5 h-3.5 bg-red-500 rounded-full" /> Data Feeder
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-700 uppercase ml-1">Target Item</label>
                    <select className="w-full bg-black/40 border border-white/10 p-4 rounded-xl text-xs font-bold text-zinc-300 outline-none" onChange={(e) => handleItemSelect(parseInt(e.target.value))}>
                      <option value="">아이템 선택...</option>
                      {items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-700 uppercase ml-1">Trade Date</label>
                    <input type="date" className="w-full bg-black/40 border border-white/10 p-4 rounded-xl text-xs font-mono text-zinc-300 outline-none" value={form.tradeDate} onChange={e => setForm({ ...form, tradeDate: e.target.value })} />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-zinc-700 uppercase ml-1">Trade Price</label>
                  <input type="text" placeholder="0" className="w-full bg-black/40 border border-white/10 p-6 rounded-2xl text-4xl font-black font-mono text-yellow-500 outline-none" value={form.price} onChange={e => setForm({ ...form, price: e.target.value.replace(/[^0-9]/g, '') })} />
                </div>
                <button onClick={handleSubmitHistory} disabled={isLoading} className="w-full py-5 bg-red-600 hover:bg-red-500 text-white font-black rounded-2xl text-sm transition-all disabled:opacity-50 shadow-xl shadow-red-900/20">
                  {isLoading ? "분석 중..." : "엔진 데이터 강제 주입"}
                </button>
              </div>

              {/* 세부 옵션 설정 (오른쪽 패널) */}
              <div className="bg-black/40 border border-white/5 p-8 rounded-[40px] max-h-[550px] overflow-y-auto custom-scrollbar">
                {selectedItem ? (
                  <div className="space-y-8">
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] font-black text-zinc-500 uppercase">Enhance Level</span>
                      <span className="text-xl font-black text-white italic">+{form.level}</span>
                    </div>
                    <input type="range" min="0" max="15" value={form.level} onChange={e => setForm({ ...form, level: parseInt(e.target.value) })} className="w-full h-1.5 bg-zinc-800 rounded-lg appearance-none accent-red-500 cursor-pointer" />

                    {selectedItem.category.toUpperCase().includes("RPG") && currentWeaponSkillConfig && (
                      <div className="space-y-4 pt-6 border-t border-white/5">
                        <div className="text-[11px] font-black text-purple-500 uppercase tracking-widest border-l-4 border-purple-500 pl-4">Combat Skills (Injection)</div>
                        <div className="grid grid-cols-2 gap-2">
                          {Object.keys(currentWeaponSkillConfig.skills).map(name => (
                            <button key={name} onClick={() => toggleSkill(name)} className={`p-4 rounded-xl border transition-all flex justify-between items-center ${form.skills[name] ? "bg-purple-600 border-purple-400 text-white" : "bg-white/5 border-transparent text-zinc-600"}`}>
                              <span className="font-bold text-xs">{name}</span>
                              {form.skills[name] && <span className="bg-white/20 px-2 py-0.5 rounded-md text-[10px] font-black">Lv.{form.skills[name]}</span>}
                            </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ) : <div className="h-full flex items-center justify-center opacity-20 text-[10px] font-black uppercase tracking-widest text-zinc-500">Select Item to Configure</div>}
              </div>
            </section>
          </motion.div>
        )}

        {activeManageTab === "DATABASE" && (
          <motion.div key="database" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white/[0.02] border border-white/5 p-8 rounded-[40px] space-y-6">
            <div className="flex justify-between items-center mb-4">
              <div className="text-sm font-black text-zinc-400 flex items-center gap-3">
                <div className="w-1 h-3 bg-cyan-500 rounded-full" /> 아이템 데이터베이스 관리
              </div>
              <button
                onClick={() => { triggerHaptic(); setIsAddingItem(!isAddingItem); }}
                className={`px-6 py-2.5 rounded-xl font-black text-xs transition-all ${isAddingItem ? "bg-zinc-800 text-zinc-500" : "bg-cyan-600 text-white shadow-lg shadow-cyan-900/20"}`}
              >
                {isAddingItem ? "닫기" : "+ 아이템 추가"}
              </button>
            </div>

            {/* 아이템 추가 폼 */}
            <AnimatePresence>
              {isAddingItem && (
                <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="grid grid-cols-1 md:grid-cols-4 gap-4 bg-black/40 p-6 rounded-3xl border border-white/10 mb-8 overflow-hidden shadow-2xl">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-600 uppercase ml-1">Icon Image</label>
                    <input type="file" accept="image/*" onChange={e => setSelectedFile(e.target.files?.[0] || null)} className="w-full text-[10px] bg-zinc-900/50 border border-white/5 p-2 rounded-xl text-zinc-400 outline-none" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-600 uppercase ml-1">Item Name</label>
                    <input type="text" placeholder="아이템명..." value={newItem.name} onChange={e => setNewItem({ ...newItem, name: e.target.value })} className="w-full bg-zinc-900/50 border border-white/5 p-3 rounded-xl text-xs font-bold text-white outline-none focus:border-cyan-500/50" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-600 uppercase ml-1">Category</label>
                    <select value={newItem.category} onChange={e => setNewItem({ ...newItem, category: e.target.value })} className="w-full bg-zinc-900/50 border border-white/5 p-3 rounded-xl text-xs font-bold text-white outline-none focus:border-cyan-500/50">
                      <option value="WILD">야생 (WILD)</option>
                      <option value="ISLAND">아일랜드 (ISLAND)</option>
                      <option value="RPG">RPG 무기</option>
                      <option value="ETC">기타 아이템 (ETC)</option>
                    </select>
                  </div>
                  <button onClick={handleCreateItem} disabled={isLoading} className="bg-white text-black font-black py-3 rounded-xl text-xs self-end mb-0.5 hover:bg-cyan-500 transition-all disabled:opacity-50">
                    {isLoading ? "등록 중..." : "아이템 등록 완료"}
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* 아이템 리스트 */}
            <div className="space-y-2 max-h-[600px] overflow-y-auto pr-2 custom-scrollbar">
              {items.map(item => (
                <div key={item.id} className="bg-black/40 p-4 rounded-2xl flex justify-between items-center border border-white/5 group hover:bg-white/[0.02] transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-zinc-900 rounded-xl flex items-center justify-center p-2 border border-white/5">
                      <img src={getSecureUrl(item.iconUrl)} className="w-full h-full object-contain pixel-art" alt={item.name} />
                    </div>
                    <div>
                      <div className="font-black text-sm text-zinc-200 uppercase">{item.name}</div>
                      <div className="text-[9px] text-zinc-600 font-black uppercase tracking-widest">{item.category}</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <span className="text-[10px] font-mono text-zinc-800">UID: #{item.id}</span>
                    <button onClick={() => purgeItem(item.id)} className="text-[10px] font-black text-zinc-800 group-hover:text-red-500 transition-colors px-4 py-2 bg-white/5 rounded-lg border border-white/5">DELETE</button>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* 거래 기록 관리 탭 */}
        {activeManageTab === "HISTORY" && (
          <motion.div key="history" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white/[0.02] border border-white/5 rounded-[40px] overflow-hidden shadow-2xl">
            <div className="p-8 border-b border-white/5 text-sm font-black text-zinc-400 flex justify-between items-center">
              <span>전체 거래 기록 리스트</span>
              <span className="text-[10px] font-black text-zinc-600">Total: {marketHistory.length}</span>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead className="bg-white/5 text-[10px] font-black text-zinc-600 uppercase tracking-widest">
                  <tr>
                    <th className="p-6">Item</th>
                    <th className="p-6">Price</th>
                    <th className="p-6">Date</th>
                    <th className="p-6">Status</th>
                    <th className="p-6 text-right">Management</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {marketHistory.map(h => (
                    <tr key={h.id} className="text-xs hover:bg-white/[0.01] transition-colors group">
                      <td className="p-6 font-bold text-zinc-300">
                        {h.item?.name} <span className="text-zinc-600 ml-1">+{h.enhancementLevel}</span>
                      </td>
                      <td className="p-6 font-mono text-cyan-500 font-black text-sm">
                        {Number(h.price).toLocaleString()} G
                      </td>
                      <td className="p-6 text-zinc-500 font-mono text-[10px]">
                        {new Date(h.tradeDate).toLocaleDateString()}
                      </td>
                      <td className="p-6">
                        <span className={`px-2.5 py-1 rounded-md text-[9px] font-black border ${h.isValid ? "bg-green-500/5 text-green-500 border-green-500/20" : "bg-red-500/5 text-red-500 border-red-500/20"}`}>
                          {h.isValid ? "VALID DATA" : "INVALID"}
                        </span>
                      </td>
                      <td className="p-6 text-right">
                        <button onClick={() => purgeHistory(h.id)} className="text-[10px] font-black text-zinc-800 hover:text-red-500 transition-colors px-3 py-1.5 bg-white/5 rounded-lg border border-white/5 opacity-0 group-hover:opacity-100">PURGE</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}